###########################################################################################
### Example 10.2. Low-pass filtering of carbon monoxide levels using the moving average ###
###########################################################################################

### Daily maximum eight hour CO concentrations New York Site ID 340130003
NYCO_2013<-read.csv("CO_2013_SiteNY340130003.csv",header=TRUE)

library(stats)
ts.plot(NYCO_2013$Daily.Max.8.hour.CO.Concentration,
        ylab="Max Daily 8 hour CO Level (ppm)", 
        xlab="Day in 2013")

### We now filter the series using a sequence of successively smoother
### plots generated by moving averages with n denoting the range of the 
### smooth moving average (SMA)
library("TTR")
NYCO_2013_DailyCO_SMA1 <- as.vector(NYCO_2013$Daily.Max.8.hour.CO.Concentration)
plot.ts(NYCO_2013_DailyCO_SMA1,xlab="",ylab="CO concentrations (ppm)",main="Single day",type="l")

### Add loess smooth
Day<-c(1:345)
CO<- NYCO_2013_DailyCO_SMA1 # Just to simplify notation
CO.loess<-loess(CO ~ Day, span=0.75,data.frame(x=Day, y = CO))
CO.predict<-predict(CO.loess,data.frame(x=Day))
lines(Day, CO.predict,lwd= 2,)

NYCO_2013_DailyCO_SMA3 <- SMA(NYCO_2013_DailyCO,n=3)
plot.ts(NYCO_2013_DailyCO_SMA3,xlab="",ylab="",main="Three day",type="l")
lines(Day, CO.predict,lwd= 2,)

NYCO_2013_DailyCO_SMA6 <- SMA(NYCO_2013_DailyCO,n=6)
plot.ts(NYCO_2013_DailyCO_SMA6,xlab="Day in 2013",ylab="CO concentrations (ppm)",main="Six day",type="l")
lines(Day, CO.predict,lwd= 2,)

NYCO_2013_DailyCO_SMA48 <- SMA(NYCO_2013_DailyCO,n=48)
plot.ts(NYCO_2013_DailyCO_SMA48,xlab="Day in 2013",ylab="",main="Forty eight day",type="l")
lines(Day, CO.predict,lwd= 2,)
